### ISSUE TITLE
Fix installation 

### ISSUE THREAD

**Issue by LukasNickel** [cta-observatory/lstmcpipe#103]
After installation, the `onsite` scripts are available, but they expect some files, e.g. the `core_list.sh` to lie in the working directory.
I am not sure if there is a way to link them in the installation process or if they would need to be generated by the python scripts ( The source env is already changed that way, so thats probably the easiest way)

`batch_dl1_utils-merge_and_copy.py` on the other hand just needs a function, that can be imported

**Comment by garciagenrique** [comment]
`batch_dl1_utils-merge_and_copy.py` is a bit tricky. How can you `batch` (in La Palma cluster) a job without this one being a script ? I didn't find another way to do it :)

**Comment by garciagenrique** [comment]
The bash scripts' problem is also know. The bash files could be installed with the package (no problem up to here). The problem is that the pipeline modifies this files in certain occasions (when the source env is modified), so modifying the installed bash file will have not effect.

**Comment by LukasNickel** [comment]
>  The problem is that the pipeline modifies this files in certain occasions (when the source env is modified)

You can export an enviroment with `subprocess`.
Not sure if I miss a problem here, but I think it would avoid the modification of the bash scripts
