### ISSUE TITLE
Define a test/demo case 

### ISSUE THREAD

**Issue by LukasNickel** [cta-observatory/lstmcpipe#108]
The current code seems to be assume that all MC files will be processed and they are all processed.
A common test folder might be useful

**Comment by garciagenrique** [comment]
Automatising this in a CI process is challenging...However, currently it exists a way of easily creating (by symlinking) a small production of the current AllSky MC prod on any desired path
https://github.com/cta-observatory/lstmcpipe/blob/master/lstmcpipe/scripts/generate_test_lapalma.py
