### ISSUE TITLE
Reenable N_R0_PER_DL1_JOB

### ISSUE THREAD

**Issue by LukasNickel** [cta-observatory/lstmcpipe#112]
As far as I can tell, this is not actually used when calling r0 to dl3.
Might be useful to set this in the config in order to balance the load on cluster

**Comment by garciagenrique** [comment]
> As far as I can tell, this is not actually used when calling r0 to dl3.

Correct. 

however please note that, the `N_R0_PER_DL1_JOB` is 'particle'-dependant (protons are 2 times more in terms of files and they take longer to run).

**Comment by LukasNickel** [comment]
Yes, as long as everything is submitted to the short queue, there is probably not much point of making it configurable.
I think we should just revisit the arguments each stage gets.
