### ISSUE TITLE
trainpipe memory limit

### ISSUE THREAD

**Issue by LukasNickel** [cta-observatory/lstmcpipe#140]
If images are processed, the standard memory might not be enough.
Maybe we should apply some heuristic or just set some large value

**Comment by garciagenrique** [comment]
You are right. 
Same for reprocessing dl1 files.

We would need to do some tests and check memory values from the slurm logs. I would suggest to use some large values for the training (and other stages) sbatch jobs

**Comment by LukasNickel** [comment]
It should actually not matter, because only the parameters table is loaded into the RAM.
Anyway, 5GB might not be enough in the future and we also might want to use more than 1 core as training is pretty slow this way.
(Especially if we want fine-tuned models for each observation soon)

**Comment by vuillaut** [comment]
Hi.
The training already uses more than 1 processor:
https://github.com/cta-observatory/cta-lstchain/blob/d6b6fb183878e11da0a5f3c23821b201f33a9a5a/lstchain/data/lstchain_standard_config.json#L83

Altough I suppose  lstmcpipe  should handled that at higher level  by:
- requesting N cores  in the slurm  job config
- applying `n_job=-1` (or `n_job=N`) in lstchain config to use all  requested cores

**Comment by LukasNickel** [comment]
lstchain uses more than 1 thread, but we only request one core.

**Comment by LukasNickel** [comment]
https://github.com/cta-observatory/lstmcpipe/blob/5c78a8f3c422fbba92f945aae06b8b48ccc1f5ea/lstmcpipe/stages/mc_train.py#L194
