### ISSUE TITLE
No IRFs from node_theta_60.528_az_175.158 in all prods

### ISSUE THREAD

**Issue by aaguasca** [cta-observatory/lstmcpipe#309]
Dear developers, 
The IRFs for the node theta_60.528_az_175.158 is not available in any production.

**Comment by aaguasca** [comment]
The same for node_theta_52.374_az_175.158_.

**Comment by vuillaut** [comment]
All the missing IRFs (for all prods) should be OK now.
Thank you for letting us know @aaguasca - please reopen if there are still missing IRFs.
