### ISSUE TITLE
Doubt in RF features to run DL1ab pipeline of 20221027_v0.9.9_base_prod

### ISSUE THREAD

**Issue by aaguasca** [cta-observatory/lstmcpipe#369]
Dear developers,

**Description**
I want to rerun the AllSky production 20220523_dec_413_tuned_nsb to take into account all the changes in lstchain up to lstchain-v0.9.9. Now, I would like to use 20221027_v0.9.9_base_prod as the source prod. I plan to use lstmcpipe v0.9.

**Doubt**
I do not know what RF features I should consider in the lstchain config. file. Should I use the same features that are used in 20221027_v0.9.9_base_prod? For example, I doubt whether I should use `sin_az_tel` or `az_tel`. Also, in the particle_classification_features, should I use `signed_skewness` and `signed_time_gradient` instead of `skewness` and `time_gradient`?

RF features of 20221027_v0.9.9_base_prod:

```
    "energy_regression_features": [
        "log_intensity",
        "width",
        "length",
        "x",
        "y",
        "wl",
        "skewness",
        "kurtosis",
        "time_gradient",
        "leakage_intensity_width_2",
        "sin_az_tel",
        "alt_tel"
    ],
    "disp_method": "disp_norm_sign",
    "disp_regression_features": [
        "log_intensity",
        "width",
        "length",
        "wl",
        "skewness",
        "kurtosis",
        "time_gradient",
        "leakage_intensity_width_2",
        "sin_az_tel",
        "alt_tel"
    ],
    "disp_classification_features": [
        "log_intensity",
        "width",
        "length",
        "wl",
        "skewness",
        "kurtosis",
        "time_gradient",
        "leakage_intensity_width_2",
        "sin_az_tel",
        "alt_tel"
    ],
    "particle_classification_features": [
        "log_intensity",
        "width",
        "length",
        "x",
        "y",
        "wl",
        "signed_skewness",
        "kurtosis",
        "signed_time_gradient",
        "leakage_intensity_width_2",
        "log_reco_energy",
        "reco_disp_norm",
        "reco_disp_sign",
        "sin_az_tel",
        "alt_tel"
    ],
```

**Comment by vuillaut** [comment]
Thank you @moralejo !

@aaguasca 
If you will have access to real data processed with lstchain >= 0.9.7, go with `sin_az_tel`. 
To generate the config, please refer to https://cta-observatory.github.io/lstmcpipe/pipeline.html#dl1ab

**Comment by aaguasca** [comment]
Okay, I will use the above features but with `az_tel` instead of `sin_az_tel` because the source of interest for this production culminates in the south. Furthermore, I think we prefer not to re-run the real data from the raw files:)

Thank you very much @moralejo, @vuillaut!
