### ISSUE TITLE
No DL2 MC files produced in two nodes due to slurm timeout

### ISSUE THREAD

**Issue by morcuended** [cta-observatory/lstmcpipe#438]
Missing DL2 files in `node_theta_52.374_az_197.973_` and `node_theta_52.374_az_49.119_`
```
/fefs/aswg/data/mc/DL2/AllSky/20231024_v0.10.4_base_dec_min_2924_min_1802_6166/TestingDataset/dec_min_2924/node_theta_52.374_az_197.973_
.../node_theta_52.374_az_49.119_
```
due to exceeded time limit (from the error log):
```
slurmstepd: error: *** JOB 28907390 ON cp35 CANCELLED AT 2023-10-25T21:01:27 DUE TO TIME LIMIT ***
```
Is it possible to produce these files?

**Comment by vuillaut** [comment]
Hi @morcuended 
Thanks for reporting this!
I will have a look.

**Comment by vuillaut** [comment]
I restarted jobs for  these two nodes
