### ISSUE TITLE
Update the default versions of lstchain and lstmcpipe?

### ISSUE THREAD

**Issue by moralejo** [cta-observatory/lstmcpipe#458]
When running the lstmcpipe_generate_config the default versions written in the yaml are lstchain v0.9.13 and lstmcpipe 0.10.3
I think we should not run any more MC with lstchain v0.9 (note that v0.10 is actually ok even for analyzing v0.9 DL1 real data)

**Comment by vuillaut** [comment]
The lstchain default version is actually `v0.10.7` when using lstmcpipe `v0.10.4`
The lstmcpipe version written in the yml file is actually the one that has been used to generate the config for provenance and reproducibility (it should not be modified by the user).
