### ISSUE TITLE
Failing prod 20240716_v0.10.7_src10_dec3476_tuned

### ISSUE THREAD

**Issue by vuillaut** [cta-observatory/lstmcpipe#471]
Hi @ToraTherese 

Unfortunately this is failing because 
```
/fefs/aswg/data/mc/DL1/AllSky/20240430_v0.10.4_src9_dec3476_tuned/TrainingDataset/dec_3476/GammaDiffuse/
```
is empty 😬 

The dataset had been separated in train/test ones:
```
/fefs/aswg/data/mc/DL1/AllSky/20240430_v0.10.4_src9_dec3476_tuned/Split_TestDataset/
/fefs/aswg/data/mc/DL1/AllSky/20240430_v0.10.4_src9_dec3476_tuned/Split_TrainingDataset/
```

So you could start from these and do the dl1ab stage without the train/test split stage, e.g.:
```
input:  /fefs/aswg/data/mc/DL1/AllSky/20240430_v0.10.4_src9_dec3476_tuned/Split_TrainingDataset/dec_3476/GammaDiffuse/node_corsika_theta_12.829_az_301.263_/
output: /fefs/aswg/data/mc/DL1/AllSky/20240716_v0.10.7_src10_dec3476_tuned/Split_TrainingDataset/dec_3476/GammaDiffuse/node_corsika_theta_12.829_az_301.263_
```
etc... 

opening an issue...

_Originally posted by @vuillaut in https://github.com/cta-observatory/lstmcpipe/issues/470#issuecomment-2233557514_

**Comment by ToraTherese** [comment]
Sorry about that, and thanks for the advice!
I've modified the config to start with the already existing split datasets, committed it to the branch, and submitted a new pull request
